name: Deploy mathwithmark.com

on:
  push:
    branches: ['main']
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "18"
          cache: npm
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3.0.5
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
